version: '2'
services:
  webapp:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8088:8088"
    depends_on:
      - db
    env_file: .env
  db:
    image: postgres:9.6.3
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data/todo

